### ISSUE TITLE
[BUG]: profile picture not updating in the feed

### ISSUE THREAD

**Issue by sofiabaezzato** [sofiabaezzato/toolbox-app#24]
After updating the profile picture, it is not updating in the cards shown in the main feed. The new profile picture is displayed correctly in  the navbar and in the profile feed.

1. Update the profile picture in the setting page
2. Go back to the home page

**Comment by rosariospalla** [comment]
I just upload my profile image and wanted to report the same thing.
Also i want to add that maybe there are little problem with the aspect ratio of the profile image.

**Comment by sofiabaezzato** [comment]
Thank you for addressing the issue. I believe it may be related to how Vercel caches images for optimization. I'm currently working on resolving the bug.

**Comment by sofiabaezzato** [comment]
Now profile picture should update as expected ✅
